spring.datasource.url=jdbc:mysql://localhost:3306/databaseCategory
spring.datasource.username=root
spring.datasource.password=arodar09
spring.datasource.driverClassName=com.mysql.jdbc.Driver

#Carpeta de archivos
app.upload.dir=uploads

spring.security.user.name=ADMIN
spring.security.user.password=ADMIN